### ISSUE TITLE
Nulls sent back from API

### ISSUE THREAD

**Issue by mikeduncangps** [snicholson-qualys/container_vuln_csv#5]
When we run the script, we noticed that instead of int's being returned as values for the keys in image['vulnerabilities'] (e.g. image['vulnerabilities']['severity1Count']), Null's were being returned instead. According to the [Qualys API docs](https://www.qualys.com/docs/qualys-container-security-api-guide.pdf), this should not be, but have you experienced this in the past? 

To locate and get around this issue, we added the following on lines of code starting at line 225...
```
        if "updated" in image.keys() and args.recordprogress:
            lastUpdated = image["updated"]
            if (lastUpdated is not None) and (lastUpdated > maxUpdated):
              maxUpdated = lastUpdated

        logger.debug(json.dumps(image))

        if "vulnerabilities" in image.keys():
            for key in image['vulnerabilities'].keys():
                if image['vulnerabilities'][key] is None:
                    image['vulnerabilities'][key] = 0

        image_detail_list = ''
        image_details_url_status = ''
```

We also noticed that after these changes and that there were no vulnerabilities reported back from the API, the script will fail on line ~309...
```
        return reportData['imageDataShare'], maxUpdated
```
 
...because reportData['imageDataShare'] will not be initialized unless there are reported vulnerabilities returned from the API. 

Thanks.

**Comment by snicholson-qualys** [comment]
New version accounts for nulls in the image and container vuln counts - updated version also moved to the v1.3 API and utilizing the Qualys API gateway. Added some sanity debug logging as well.
